version: "3.9"

services:
  product-service:
    image: alpine/java:21-jdk
    container_name: product-service
    #restart: always
    ports:
      - "9002:9002"
    volumes:
      - ./target/product-service-0.0.1-SNAPSHOT.jar:/app/product-service-v1.jar
    command: ["java", "-jar", "/app/product-service-v1.jar"]
    networks:
      - mitocode

networks:
  mitocode:
    name: mitocode-network